# This file has been autogenerated in 'extras/ModuleMaintenance.R'. Do not change by hand.
createCharacterizationModuleSpecifications <- function(
    targetIds,
    outcomeIds, # a vector of ids
    outcomeWashoutDays = c(365), # same length as outcomeIds with the outcomeWashout
    dechallengeStopInterval = 30,
    dechallengeEvaluationWindow = 30,
    timeAtRisk = data.frame(
      riskWindowStart = c(1, 1),
      startAnchor = c("cohort start", "cohort start"),
      riskWindowEnd = c(0, 365),
      endAnchor = c("cohort end", "cohort end")
    ),
    minPriorObservation = 365,
    minCharacterizationMean = 0.01,
    covariateSettings = FeatureExtraction::createCovariateSettings(
      useDemographicsGender = T,
      useDemographicsAge = T,
      useDemographicsAgeGroup = T,
      useDemographicsRace = T,
      useDemographicsEthnicity = T,
      useDemographicsIndexYear = T,
      useDemographicsIndexMonth = T,
      useDemographicsTimeInCohort = T,
      useDemographicsPriorObservationTime = T,
      useDemographicsPostObservationTime = T,
      useConditionGroupEraLongTerm = T,
      useDrugGroupEraOverlapping = T,
      useDrugGroupEraLongTerm = T,
      useProcedureOccurrenceLongTerm = T,
      useMeasurementLongTerm = T,
      useObservationLongTerm = T,
      useDeviceExposureLongTerm = T,
      useVisitConceptCountLongTerm = T,
      useConditionGroupEraShortTerm = T,
      useDrugGroupEraShortTerm = T,
      useProcedureOccurrenceShortTerm = T,
      useMeasurementShortTerm = T,
      useObservationShortTerm = T,
      useDeviceExposureShortTerm = T,
      useVisitConceptCountShortTerm = T,
      endDays = 0,
      longTermStartDays =  -365,
      shortTermStartDays = -30
    ),
    caseCovariateSettings = Characterization::createDuringCovariateSettings(
      useConditionGroupEraDuring = T,
      useDrugGroupEraDuring = T,
      useProcedureOccurrenceDuring = T,
      useDeviceExposureDuring = T,
      useMeasurementDuring = T,
      useObservationDuring = T,
      useVisitConceptCountDuring = T
    ),
    casePreTargetDuration = 365,
    casePostOutcomeDuration = 365
) {
  # input checks
  if (!inherits(timeAtRisk, "data.frame")) {
    stop("timeAtRisk must be a data.frame")
  }
  if (nrow(timeAtRisk) == 0) {
    stop("timeAtRisk must be a non-empty data.frame")
  }

  if(!inherits(outcomeIds, "numeric")){
    stop("outcomeIdsList must be a numeric or a numeric vector")
  }

  if(!inherits(outcomeWashoutDays, "numeric")){
    stop("outcomeWashoutDays must be a numeric or a numeric vector")
  }
  if(length(outcomeIds) != length(outcomeWashoutDays)){
    stop("outcomeWashoutDaysVector and outcomeIdsList must be same length")
  }

  # group the outcomeIds with the same outcomeWashoutDays
  outcomeWashoutDaysVector <- unique(outcomeWashoutDays)
  outcomeIdsList <- lapply(
    outcomeWashoutDaysVector,
    function(x){
      ind <- which(outcomeWashoutDays == x)
      unique(outcomeIds[ind])
    }
  )


  timeToEventSettings <- Characterization::createTimeToEventSettings(
    targetIds = targetIds,
    outcomeIds = outcomeIds
  )

  dechallengeRechallengeSettings <- Characterization::createDechallengeRechallengeSettings(
    targetIds = targetIds,
    outcomeIds = outcomeIds,
    dechallengeStopInterval = dechallengeStopInterval,
    dechallengeEvaluationWindow = dechallengeEvaluationWindow
  )

  aggregateCovariateSettings <- list()

  for(i in 1:nrow(timeAtRisk)){
    for(j in 1:length(outcomeIdsList)){
      aggregateCovariateSettings[[length(aggregateCovariateSettings) + 1]] <- Characterization::createAggregateCovariateSettings(
        targetIds = targetIds,
        outcomeIds = outcomeIdsList[[j]],
        outcomeWashoutDays = outcomeWashoutDaysVector[j],
        minPriorObservation = minPriorObservation,
        riskWindowStart = timeAtRisk$riskWindowStart[i],
        startAnchor = timeAtRisk$startAnchor[i],
        riskWindowEnd = timeAtRisk$riskWindowEnd[i],
        endAnchor = timeAtRisk$endAnchor[i],
        covariateSettings = covariateSettings,
        caseCovariateSettings = caseCovariateSettings,
        casePreTargetDuration = casePreTargetDuration,
        casePostOutcomeDuration = casePostOutcomeDuration,
        minCharacterizationMean = minCharacterizationMean
      )
    }
  }

  analysis <- Characterization::createCharacterizationSettings(
    timeToEventSettings = list(timeToEventSettings),
    dechallengeRechallengeSettings = list(dechallengeRechallengeSettings),
    aggregateCovariateSettings = aggregateCovariateSettings
  )

  specifications <- list(
    module = "CharacterizationModule",
    version = "0.7.0-4",
    remoteRepo = "github.com",
    remoteUsername = "ohdsi",
    settings = analysis
  )
  class(specifications) <- c("CharacterizationModuleSpecifications", "ModuleSpecifications")
  return(specifications)
}
